# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Open Banking Documentation
site_description: Documentation for WSO2 Open Banking
site_author: WSO2
site_url: https://ob.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/docs-open-banking
repo_url: https://github.com/wso2/docs-open-banking
edit_uri: https://github.com/wso2/docs-open-banking/edit/master/en/docs/

# Copyright
copyright: WSO2 Open Banking - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Get Started':
    - 'Open Banking': get-started/open-banking.md
    - 'Open Banking Requirements': get-started/open-banking-requirements.md
    - 'Regulations and Standards': get-started/regulations-and-standards.md
    - 'WSO2 Open Banking Accelerator': get-started/wso2-open-banking-accelerator.md
    - 'About this Release': get-started/about-this-release.md
    - 'Quick Start Guide':
      - 'Get Started': get-started/quick-start-guide.md
      - 'Set Up Accelerators': get-started/set-up-accelerators.md
      - 'Configure Users and Roles': get-started/configure-users-and-roles.md
      - 'Dynamic Client Registration': get-started/dynamic-client-registation.md
      - 'Tryout Flow': get-started/try-out-flow.md
      - 'Data Publishing': get-started/data-publishing-try-out.md
  - 'Install and Setup':
    - 'Prerequisites': install-and-setup/prerequisites.md
    - 'Setting up servers': install-and-setup/setting-up-servers.md
    - 'Setting up databases': install-and-setup/setting-up-databases.md
    - 'Configuring Identity Server': install-and-setup/configuring-identity-server-for-ob.md
    - 'Configuring API Manager': install-and-setup/configuring-api-manager-for-ob.md
    - 'Deploy with Docker' : install-and-setup/deploy-with-docker.md
    - 'Configuring Users and Roles': install-and-setup/configuring-users-and-roles.md
    - 'Troubleshooting': install-and-setup/troubleshooting.md
  - 'Learn':
    - 'Consent Management':
      - 'Introduction': learn/consent-management.md
      - 'Tryout': learn/consent-management-try-out.md
      - 'Consent Manager': learn/consent-manager.md
    - 'Consent Authorization': learn/consent-authorization-intro.md
    - 'Token Authentication': learn/token-authentication.md
    - 'Dynamic Client Registration':
      - 'Introduction': learn/dynamic-client-registration.md
      - 'Configuration': learn/dynamic-client-registration-configuration.md
      - 'Tryout': learn/dynamic-client-registration-try-out.md
    - 'Consumer Authentication':
      - 'Introduction': learn/consumer-authentication.md
      - 'App-to-App Redirection': learn/app-to-app-redirection.md
      - 'Identifier-first Authentication': learn/identifier-first.md
    - 'CIBA Flow':
      - 'Introduction': learn/ciba.md
      - 'Set up CIBA flow': learn/ciba-set-up-flow.md
      - 'CIBA with sample application': learn/ciba-with-sample-react-native-app.md
    - 'Event Notification':
      - 'Introduction': learn/event-notification.md
      - 'Configuration': learn/event-notification-configuration.md
    - 'API Security':
      - 'Introduction': learn/api-security.md
      - 'Configuration': learn/api-security-configuration.md
    - 'Data Publishing':
      - 'Introduction': learn/data-publishing.md
      - 'Tryout': learn/data-publishing-tryout.md
    - 'Integration': learn/integration.md
  - 'Develop' :
    - 'Toolkit Introduction': develop/develop-toolkit.md
    - 'Developer Guide': develop/developer-guide.md
    - 'Open Banking Gateway' :
        - 'Introduction': develop/open-banking-gateway.md
        - 'Custom Request Router': develop/custom-request-router.md
        - 'Custom Gateway Executor': develop/custom-gateway-executor.md
        - 'Custom API Consumer Validation Executor': develop/custom-api-consumer-validation.md
        - 'Error handling in API Gateway': develop/gateway-error-handling.md
        - 'Custom Throttling Keys': develop/custom-throttling-keys.md
    - 'Open Banking Event Executor':
        - 'Custom Event Executor': develop/custom-event-executor.md
    - 'Consent Management':
        - 'Consent Manage': develop/consent-management-manage.md
        - 'Consent Validate': develop/consent-management-validate.md
        - 'Consent Authorize': develop/consent-management-authorize.md
        - 'Consent Enforcement Executor': develop/consent-enforcement-executor.md
        - 'Consent Core Service': develop/consent-core-service.md
        - 'Customize the Consent Page': develop/customize-consent-page.md
    - 'Token Flow Customization':
        - 'JWT Access Tokens': develop/jwt-access-tokens.md
        - 'Token Filters': develop/token-filters.md
        - 'Grant Handlers': develop/grant-handlers.md
        - 'Introspection Data Provider': develop/introspection-data-provider.md
        - 'Custom Claim Provider': develop/custom-claim-provider.md
        - 'ID Token Builder': develop/id-token-builder-token-flow.md
    - 'Authentication Flow':
        - 'Customize Authentication Steps' : develop/customize-authentication-steps.md
        - 'CIBA Push Authenticator': develop/ciba-push-authenticator.md
        - 'CIBA Consent Updater': develop/ciba-consent-updater.md
    - 'Authorization Flow':
        - 'KeyID Provider': develop/keyid-provider.md
        - 'ID Token Builder': develop/id-token-builder-auth-flow.md
        - 'Response Type Handler': develop/response-type-handler.md
        - 'Custom Request Object Validator': develop/custom-request-object-validator.md
        - 'Custom Pushed Auth Request Validator': develop/custom-pushed-auth-request-validator.md
    - 'Mobile Application for CIBA': develop/mobile-application-for-ciba.md
    - 'Additional Application Property Validation': develop/application-property-validation.md
    - 'Dynamic Client Registration':
        - 'Application Management Listener': develop/application-management-listener.md
        - 'Custom DCR Validator': develop/custom-dcr-validator.md
    - 'Event Notification': develop/custom-event-notification.md
    - 'Using Hibernate Validator': develop/validation-layer.md
    - 'Data Publishing':
        - 'Custom Data Publishing': develop/custom-data-publishing.md
        - 'Authentication Flow': develop/authentication-flow-for-data-publishing.md
        - 'Dynamic Client Registration': develop/dcr-for-data-publishing.md
        - 'Token Data Publishing' : develop/token-data-publishing.md
  - 'References':
    - 'Identity Server Configuration Catalog': references/config-catalog-is.md
    - 'API Manager Configuration Catalog': references/config-catalog-apim.md
    - 'Consent REST API': references/consent-rest-api.md
    - 'DCR REST API': references/dcr-rest-api.md
    - 'Application Info API': references/application-info-api.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 3.0.0
  nav_list:
    - Home
    - Get Started
    - Install and Setup
    - Learn
    - Develop
    - References